[build]
  publish = "."

[[redirects]]
  from = "/materi%20PJOK%20BAB%203.html"
  to = "/materi/pjok-kelas-3-bab-3.html"
  status = 301

[[redirects]]
  from = "/materi%20Informatika%20BAB%207.html"
  to = "/materi/informatika-kelas-3-bab-7.html"
  status = 301

[[redirects]]
  from = "/materi/Informatika%20materi-kelas-3-bab-7.html"
  to = "/materi/informatika-kelas-3-bab-7.html"
  status = 301

[[redirects]]
  from = "/materi/informatika-kelas-4-bab-7.html"
  to = "/materi/informatika-kelas-3-bab-7.html"
  status = 301

[[redirects]]
  from = "/materi%20Seni%20Budaya%20BAB%207.html"
  to = "/materi/seni-budaya-kelas-3-bab-7.html"
  status = 301

[[redirects]]
  from = "/materi%20Matematika%20BAB%205.html"
  to = "/materi/Matematika-kelas-3-bab-5.html"
  status = 301

[[redirects]]
  from = "/materi/matematika-kelas-3-bab-5.html"
  to = "/materi/Matematika-kelas-3-bab-5.html"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
